---
title: "final-project"
output: pdf_document
date: "2025-12-08"
---

# Merging unemployment data for states AR, CT, DE, IA, ID, INUR, KS, KY, ME, MN, MO, MT, ND, NE, NH, NM, OK, PR, RI, SC, SD, UT, VT, WV, WY
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
path <- "~/Desktop/class/datasci306/state-employment-data"

files <- list.files(path, pattern = "\\.csv$", full.names = TRUE)

data_list <- lapply(files, read.csv)
names(data_list) <- tools::file_path_sans_ext(basename(files))
```

```{r}
library(dplyr)

all_ur <- Reduce(
  function(x, y) full_join(x, y, by = "observation_date"),
  data_list
)
dim(all_ur)
head(all_ur)
```

```{r}
write.csv(all_ur, "~/Desktop/merged_unemployment.csv", row.names = FALSE)
```


# Cleaning the ALL MERGED unemployment dataset 


```{r}
path <- "~/Desktop/class/datasci306/finalproject"

files <- list.files(path, pattern = "\\.csv$", full.names = TRUE)

library(tidyverse)
df <- read_csv("unemployment.csv")
```

## Cleaning up duplicates and adding missing states
```{r}

# Fixing duplicates (KY and MN)
# Create correct KYUR by combining KYURN.x and KYURN.y
df <- df %>%
  mutate(KYUR = coalesce(KYURN.x, KYURN.y)) %>%
  select(-KYURN.x, -KYURN.y)

# Create correct MNUR by combining MNUR.x and MNUR.y (if MNUR.x doesn't exist, coalesce handles it)
df <- df %>%
  mutate(MNUR = coalesce(MNUR.x, MNUR.y)) %>%
  select(-any_of(c("MNUR.x", "MNUR.y")))   # removes whichever exist
```

```{r}
# Remove DC and PR columns (not in IRS dataset)

df <- df %>%
  select(-any_of(c("DCUR", "PRUR")))

# Add 4 more states (LA, MS, HI, AK)
extra_dir <- "state-employment-data"

extra_files <- file.path(extra_dir, c("AKUR.csv", "HIUR.csv", 
                                      "LAUR.csv", "MSUR.csv"))

extra_states <- extra_files |>
  map_df(read_csv)

# Combine Original + New
df_final <- df %>%
  full_join(extra_states, by = "observation_date")

df_final <- df_final %>%
  mutate(
    AKUR = coalesce(AKUR.x, AKUR.y),
    HIUR = coalesce(HIUR.x, HIUR.y),
    LAUR = coalesce(LAUR.x, LAUR.y),
    MSUR = coalesce(MSUR.x, MSUR.y)
  ) %>%
  select(-AKUR.x, -AKUR.y,
         -HIUR.x, -HIUR.y,
         -LAUR.x, -LAUR.y,
         -MSUR.x, -MSUR.y)

# 6. Save cleaned dataset
write_csv(df_final, "unemployment_cleaned.csv")

```


## Imputing any NA values with column means

```{r}
library(dplyr)
library(lubridate)

df <- read.csv("unemployment_cleaned.csv")

df$observation_date <- ymd(df$observation_date)

# Replace NA values with column means
df_imputed <- df |>
  mutate(across(where(is.numeric),
                ~ ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x)))
```

## Aggregate unemployment rates by year

```{r}
df_filtered <- df_imputed %>%
  filter(year(observation_date) >= 2011,
         year(observation_date) <= 2022)

# Compute yearly averages
df_yearly <- df_filtered %>%
  mutate(year = year(observation_date)) %>%
  select(-observation_date) %>%
  group_by(year) %>%
  summarise(across(everything(), ~ mean(.x, na.rm = TRUE))) %>%
  mutate(across(where(is.numeric), ~ round(.x, 3)))

write.csv(df_yearly, "unemployment_yearly_2011_2022.csv", row.names = FALSE)

```


